# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/INTRA/ahelkh/workspace/lab2/lab2/lab2.cache/wt [current_project]
set_property parent.project_path /home/INTRA/ahelkh/workspace/lab2/lab2/lab2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
add_files /home/INTRA/ahelkh/workspace/lab2/lab2/lab2.srcs/sources_1/bd/lab2_SoC/lab2_SoC.bd
set_property used_in_implementation false [get_files -all /home/INTRA/ahelkh/workspace/lab2/lab2/lab2.srcs/sources_1/bd/lab2_SoC/ip/lab2_SoC_processing_system7_0_0/lab2_SoC_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/INTRA/ahelkh/workspace/lab2/lab2/lab2.srcs/sources_1/bd/lab2_SoC/ip/lab2_SoC_axi_gpio_0_0/lab2_SoC_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/INTRA/ahelkh/workspace/lab2/lab2/lab2.srcs/sources_1/bd/lab2_SoC/ip/lab2_SoC_axi_gpio_0_0/lab2_SoC_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/INTRA/ahelkh/workspace/lab2/lab2/lab2.srcs/sources_1/bd/lab2_SoC/ip/lab2_SoC_axi_gpio_0_0/lab2_SoC_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/INTRA/ahelkh/workspace/lab2/lab2/lab2.srcs/sources_1/bd/lab2_SoC/ip/lab2_SoC_rst_processing_system7_0_100M_0/lab2_SoC_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/INTRA/ahelkh/workspace/lab2/lab2/lab2.srcs/sources_1/bd/lab2_SoC/ip/lab2_SoC_rst_processing_system7_0_100M_0/lab2_SoC_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/INTRA/ahelkh/workspace/lab2/lab2/lab2.srcs/sources_1/bd/lab2_SoC/ip/lab2_SoC_rst_processing_system7_0_100M_0/lab2_SoC_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/INTRA/ahelkh/workspace/lab2/lab2/lab2.srcs/sources_1/bd/lab2_SoC/ip/lab2_SoC_auto_pc_0/lab2_SoC_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/INTRA/ahelkh/workspace/lab2/lab2/lab2.srcs/sources_1/bd/lab2_SoC/lab2_SoC_ooc.xdc]
set_property is_locked true [get_files /home/INTRA/ahelkh/workspace/lab2/lab2/lab2.srcs/sources_1/bd/lab2_SoC/lab2_SoC.bd]

read_vhdl -library xil_defaultlib /home/INTRA/ahelkh/workspace/lab2/lab2/lab2.srcs/sources_1/bd/lab2_SoC/hdl/lab2_SoC_wrapper.vhd
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top lab2_SoC_wrapper -part xc7z020clg484-1
write_checkpoint -noxdef lab2_SoC_wrapper.dcp
catch { report_utilization -file lab2_SoC_wrapper_utilization_synth.rpt -pb lab2_SoC_wrapper_utilization_synth.pb }
